import {seedListings,seedNotifications,seedOffers,seedZones} from "@/data/seed";
import type {Listing,Offer,Zone} from "@/domain/types";
const delay=(ms=280)=>new Promise<void>(resolve=>setTimeout(resolve,ms)); const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
let listings=clone(seedListings);let offers=clone(seedOffers);let zones=clone(seedZones);
export const listingService={async getListings():Promise<Listing[]>{await delay();return clone(listings)},async getListing(id:string){await delay(160);return clone(listings.find(x=>x.id===id))},async publishDraft(input:Pick<Listing,"title"|"price"|"location">){await delay(500);const next={...seedListings[0],...input,id:`MK-${Date.now().toString().slice(-5)}`,verification:"Pending" as const,status:"Pending verification" as const,views:0,offers:0};listings=[next,...listings];return clone(next)},async markVerified(id:string){await delay(650);listings=listings.map(x=>x.id===id?{...x,verification:"Verified",status:"Active"}:x);return clone(listings.find(x=>x.id===id))}};
export const offerService={async getOffers():Promise<Offer[]>{await delay();return clone(offers)},async createOffer(listingId:string,amount:number){await delay(520);const next={id:`OF-${Date.now()}`,listingId,amount,state:"Offered" as const,actor:"You",time:"Just now"};offers=[...offers,next];return clone(next)},async acceptOffer(id:string){await delay(500);offers=offers.map(x=>x.id===id?{...x,state:"Accepted"}:x);return clone(offers.find(x=>x.id===id))}};
export const zoneService={async getZones():Promise<Zone[]>{await delay();return clone(zones)},async previewZoneChange(id:string){await delay();const z=zones.find(x=>x.id===id);return{listings:z?.affected??0,transactions:3,verifications:8}},async restrict(id:string,reason:string){await delay(600);zones=zones.map(z=>z.id===id?{...z,status:"RESTRICTED",reason}:z);if(id==="ZN-01")listings=listings.map(l=>l.province==="Midlands"?{...l,tradeability:"RESTRICTED"}:l);return clone(zones.find(x=>x.id===id))}};
export const notificationService={async getNotifications(){await delay(120);return clone(seedNotifications)}};
export const authService={async login(phone:string){await delay(450);return{id:"USR-01",name:"Tariro Moyo",phone,roles:["buyer","seller"]}},async verifyOtp(code:string){await delay(350);return code.length===6},async logout(){await delay();return true}};
